export const exchangeData = [
  {
    userId: "sjijszdziekc",
    numExchange: "AHZUHAUA123",
    serverOut: "Boune",
    serverIn: "Agride",
    qtyToPay: 100,
    characterToPay: "zirgo",
    qtyToReceive: 95,
    characterToReceive: "mopil",
    codeToExchange: "edver",
    status: "En attente",
    percent: 0.05,
    date: "22 septembre 2022",
  },

  {
    userId: "sjijszdziekcoo",
    numExchange: "FNDKJFJFPE",
    serverOut: "Agrine",
    serverIn: "Ush",
    qtyToPay: 200,
    characterToPay: "hzii",
    qtyToReceive: 190,
    characterToReceive: "zdkc",
    codeToExchange: "nbhju",
    status: "Termine",
    percent: 0.05,
    date: "22 septembre 2022",
  },

  {
    userId: "sjijszdziekcoo",
    numExchange: "FNDKJFJFPE",
    serverOut: "Ilizaelle",
    serverIn: "Ush",
    qtyToPay: 50,
    characterToPay: "hzii",
    qtyToReceive: 47.5,
    characterToReceive: "zdkc",
    codeToExchange: "nbhju",
    status: "Annule",
    percent: 0.05,
    date: "22 septembre 2022",
  },
];
